
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CLIServices.ListNugetPackagesService.WriteOutput(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{Nautilus.Cli.Core.Models.NugetPackageReferenceExtended}},System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CLIServices.ListNugetPackagesService.WriteOutput(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{Nautilus.Cli.Core.Models.NugetPackageReferenceExtended}},System.String,System.Int32,System.Collections.Generic.Dictionary{System.String,System.String})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CLIServices.ListNugetPackagesService.WriteOutput(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{Nautilus.Cli.Core.Models.NugetPackageReferenceExtended}},System.String,System.Int32,System.Collections.Generic.Dictionary{System.String,System.Object})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CLIServices.ListProjectsService.WriteToScreen(Nautilus.Cli.Core.Models.Solution,System.Action{Nautilus.Cli.Core.Models.Project})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CLIServices.ListProjectsService.ListNugetPackages(Nautilus.Cli.Core.Models.Project)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CLIServices.ListProjectsService.WriteToScreen(Nautilus.Cli.Core.Models.Solution,System.Action{Nautilus.Cli.Core.Models.Project},System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{Nautilus.Cli.Core.Models.NugetPackageInformationComparer}})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CLIServices.ListProjectsService.WriteToScreen(Nautilus.Cli.Core.Models.Solution,System.Action{Nautilus.Cli.Core.Models.Project,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{Nautilus.Cli.Core.Models.NugetPackageInformationComparer}}})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CLIServices.ListProjectsService.WriteToScreen(Nautilus.Cli.Core.Models.Solution)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CLIServices.ListProjectsService.WriteToScreen(Nautilus.Cli.Core.Models.Solution,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{Nautilus.Cli.Core.Models.NugetPackageInformationComparer}})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:Nautilus.Cli.Client.CommandLine.Services.ListProjectsService.WriteToScreen(Nautilus.Cli.Core.Models.Solution,System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{Nautilus.Cli.Core.Models.NugetPackageInformationComparer}})")]

