
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:NautilusCLI.Core.Services.FindConflictService.WriteOutput(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{NautilusCLI.Core.Models.NugetPackageReferenceExtended}})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:NautilusCLI.Core.Services.FindConflictService.WriteOutput(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{NautilusCLI.Core.Models.NugetPackageReferenceExtended}},System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:NautilusCLI.CLIServices.FindConflictService.WriteOutput(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{NautilusCLI.Core.Models.NugetPackageReferenceExtended}},System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:NautilusCLI.CLIServices.ListProjectsService.WriteToScreen(NautilusCLI.Core.Models.Solution,System.Action{NautilusCLI.Core.Models.Project})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:NautilusCLI.CLIServices.ListProjectsService.WriteToScreen(Nautilus.Cli.Core.Models.Solution,System.Action{Nautilus.Cli.Core.Models.Project})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Potential Code Quality Issues", "RECS0155:Finds issues with format strings", Justification = "<Pending>", Scope = "member", Target = "~M:NautilusCLI.CLIServices.FindConflictService.WriteOutput(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.IList{Nautilus.Cli.Core.Models.NugetPackageReferenceExtended}},System.String,System.Int32)")]

